# Generated by Django 5.0.2 on 2024-03-01 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_user_type_eventmember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmember',
            name='status',
        ),
    ]
