# Generated by Django 5.0.2 on 2024-03-01 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_remove_eventmember_attend_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmember',
            name='type',
        ),
    ]
