# Generated by Django 5.0.2 on 2024-03-01 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_remove_eventmember_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventMember',
        ),
    ]
