# Generated by Django 5.0.2 on 2024-03-01 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_delete_eventmember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='type',
        ),
    ]
