# Generated by Django 5.0.2 on 2024-03-01 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0019_delete_organizers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='participants',
        ),
    ]
