# Generated by Django 5.0.2 on 2024-03-01 19:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0021_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
    ]
