# Generated by Django 5.0.2 on 2024-03-02 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0024_alter_event_participants_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='name',
        ),
    ]
